# Generated by Django 3.2.7 on 2021-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce_text',
            field=models.CharField(blank=True, help_text='簡単な自己紹介を200文字以内で書いてください。', max_length=200, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, help_text='50文字以内です', max_length=50, verbose_name='住んでいる場所'),
        ),
    ]
