# Generated by Django 3.2.7 on 2022-03-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_day',
            new_name='created_at',
        ),
    ]
